language: node_js
sudo: required
dist: trusty

node_js:
  - "iojs"
  - "7"
  - "6"
  - "5"
  - "4"

addons:
  firefox: "latest"

install: 
 - npm install --save-dev jest

before_script:
  - echo "Running before_script against $(node -v) ..."

script:
  - echo "Running script against $(node -v) ..."
  - phantomjs lib/test.js
  - npm test
